# Generated by Django 5.0.1 on 2024-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('word_file', models.FileField(upload_to='submissions/')),
                ('excel_file', models.FileField(upload_to='submissions/')),
                ('python_file', models.FileField(upload_to='submissions/')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
