# Generated by Django 5.0.1 on 2024-01-19 03:30

import folder_upload_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_upload_app', '0002_submission_delete_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rar_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='room_no',
            field=models.CharField(default='DefaultRoomNo', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='python_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
    ]
