# Generated by Django 5.0.1 on 2024-01-19 03:35

import folder_upload_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_upload_app', '0003_submission_rar_file_submission_room_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compressed_file',
            field=models.FileField(blank=True, null=True, upload_to=folder_upload_app.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='room_no',
            field=models.CharField(max_length=100),
        ),
    ]
