# Generated by Django 5.0.1 on 2024-01-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_upload_app', '0004_submission_compressed_file_alter_submission_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rar_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='zip_file',
        ),
    ]
